name: koolbase_flutter
description: Flutter SDK for Koolbase — feature flags, remote config, version enforcement, authentication, storage, database, realtime, OTA updates, and code push for mobile apps.
version: 5.1.0
homepage: https://koolbase.com
repository: https://github.com/kennedyowusu/koolbase_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.2.0
  archive: ^4.0.9
  path_provider: ^2.1.0
  package_info_plus: ^9.0.1
  crypto: ^3.0.3
  uuid: ^4.4.0
  web_socket_channel: ^3.0.3
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  connectivity_plus: ^7.1.0
  rfw: ^1.0.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.18.0

flutter:
  # No assets or fonts needed for SDK
